language: ruby
cache: bundler
rvm:
  - 2.4.1

install:
  - bundle install --deployment --jobs=3 --retry=3
before_script:
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec

services:
  - redis-server
addons:
  postgresql: '9.6'
notifications:
  slack:
    secure: d9V7SikVD0g4xsYreSL5T4EgCmbrgPWcAoF+OHTW/MDWg50eCkB5TVHVxYDByAbYm8yCEFUFWcwEGiUrfxNfQjMc+ajyu3jgCRGy6neDj2lbf1gI2ua7r3/GWWuJd4FfQL/Uih2BJJmw3Y7Zqz/OWgNBokGEUaQrqNB3etVRyiFJLbX3BoolZQTDUmjMjCGRktvKVP8YulNZIq5G5eAJu8zT8vyTqTNiTTiucr3YrChUqYiVJsHu4mEyAe+aE4TY98BYoxwOAL/3xPaUmTBiFveOA7qqKazTolj5zbW9LXVUMedWM/udtq+ly2tAaF9YhrhkA1P6YsLulC3RdvnbxpyWeNWEcEvri6QEpcCXuqG+lESyxKc/Xf1SNcEnfZsZF9UJ/PipzZvhWA2AC2476pJFmqm84HT6mzLVUgDdgkc9P7KhaTKRWkuVLOvjaigrliQUN7o4akX0FfjvsLMDEma8g7JdQ4rhrqi+EgFeLB0d80DHIcDLOA/HdkMwZ2ct2nT6/wtwS4d1M+oJztGPAg8lCg6Reon1Dy/HoDbNbk1JUMohoV1rw67G+o2qpc21k/Xvpw1dy1dk+uBOIQ8CaEeynFnEQw7dWZPAPd2EpQ4AncrZEWdR1hfN4U1Kab/HFJukSrHEQvloeUhzk+BIJV++RCI1kqNY8VslMzZyRlE=
