language: ruby
cache: bundler
rvm:
  - 2.4.1

install:
  - bundle install --deployment --jobs=3 --retry=3
before_script:
  - bundle exec rake db:create db:schema:load
script:
  - bundle exec rspec

services:
  - redis-server
addons:
  postgresql: '10'
